# Generated by Django 3.1.7 on 2021-09-10 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('street', models.TextField(blank=True, db_index=True, help_text='Street', null=True)),
                ('city', models.TextField(blank=True, db_index=True, help_text='City', null=True)),
                ('state', models.TextField(blank=True, db_index=True, help_text='State', null=True)),
                ('country', models.TextField(blank=True, db_index=True, help_text='Country', null=True)),
                ('pincode', models.TextField(blank=True, db_index=True, help_text='Country', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'street', 'city', 'state', 'country', 'pincode')},
            },
        ),
    ]
